import { expect, test } from "@playwright/test";

test("touch outfit selection, full character and photoshoot on a phone", async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const errors: string[] = [];
  const consoleErrors: string[] = [];
  const failedRequests: string[] = [];
  const badResponses: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });
  page.on("requestfailed", (request) => {
    const reason = request.failure()?.errorText || "unknown";
    const isExpectedSafariMediaCancel = reason === "Load request cancelled" && request.url().includes("/game/Music/BackgroundMusic.mp3");
    if (!isExpectedSafariMediaCancel) failedRequests.push(`${reason} ${request.method()} ${request.url()}`);
  });
  page.on("response", (response) => {
    if (response.status() >= 400) badResponses.push(`${response.status()} ${response.url()}`);
  });
  await page.goto("/play");
  await page.getByTestId("garment-top-modal-grommet").tap();
  await page.getByTestId("mobile-category-bottoms").tap();
  await page.getByTestId("garment-bottom-sculpted-jeans").tap();
  await page.getByTestId("mobile-category-shoes").tap();
  await page.getByTestId("garment-shoes-party-platform-boots").tap();
  const stage = page.getByTestId("studio-stage");
  await expect(page.locator(".mobile-category-tabs")).toBeVisible();
  await expect(page.locator(".wardrobe-wheel")).toBeHidden();
  await expect(stage).toHaveAttribute("data-layer-count", "3");
  await stage.locator("img").evaluateAll((images) => Promise.all(images.map((image) => (image as HTMLImageElement).decode())));
  const box = (await stage.boundingBox())!;
  expect(box.height / box.width).toBeCloseTo(1.5, 1);
  expect(box.y).toBeGreaterThanOrEqual(0);
  expect(box.y + box.height).toBeLessThan((await page.getByRole("button", { name: "SHOW YOUR LOOK" }).boundingBox())!.y);
  await expect(page.getByTestId("foreground-arms")).toHaveCSS("z-index", "38");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-play.png`, scale: "css" });
  await page.getByRole("button", { name: "SHOW YOUR LOOK" }).tap();
  await expect(page.getByTestId("showcase-save-btn")).toBeVisible();
  const showcaseStage = (await page.getByTestId("studio-stage").boundingBox())!;
  expect(showcaseStage.y).toBeGreaterThanOrEqual(0);
  await page.waitForTimeout(400);
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-showcase.png`, scale: "css" });
  await page.getByTestId("showcase-save-btn").tap();
  await expect(page).toHaveURL(/\/photoshoot/, { timeout: 15000 });
  await expect(page.getByTestId("photoshoot-look")).toBeVisible();
  const actor = (await page.getByTestId("photoshoot-look").boundingBox())!;
  const frame = (await page.getByTestId("photoshoot-frame").boundingBox())!;
  expect(actor.height).toBeGreaterThan(180);
  expect(actor.y).toBeGreaterThanOrEqual(frame.y);
  expect(actor.y + actor.height).toBeLessThanOrEqual(frame.y + frame.height + 1);
  expect(actor.height / actor.width).toBeCloseTo(1.5, 1);
  await page.getByRole("link", { name: "GO BACK" }).scrollIntoViewIfNeeded();
  await expect(page.getByRole("button", { name: "SAVE", exact: true })).toBeInViewport();
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-photoshoot.png`, fullPage: true, scale: "css" });
  await page.getByRole("link", { name: "GO BACK" }).tap();
  await expect(page.locator('[data-garment="bottom-sculpted-jeans"]')).toBeVisible();
  await page.setViewportSize({ width: 844, height: 390 });
  await expect(page.locator(".figma-loading-overlay")).toBeHidden({ timeout: 15_000 });
  await expect(stage).toBeInViewport();
  await expect(page.getByRole("button", { name: "SHOW YOUR LOOK" })).toBeInViewport();
  const landscapeWheel = page.locator(".wardrobe-wheel");
  const landscapeWardrobe = page.locator(".wardrobe");
  await expect(landscapeWheel).toBeVisible();
  const landscapeWheelBox = (await landscapeWheel.boundingBox())!;
  const landscapeWardrobeBox = (await landscapeWardrobe.boundingBox())!;
  expect(Math.abs(landscapeWheelBox.x + landscapeWheelBox.width - landscapeWardrobeBox.x)).toBeLessThanOrEqual(3);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-play-landscape.png`, scale: "css" });
  await page.getByRole("button", { name: "SHOW YOUR LOOK" }).tap();
  await expect(page.getByTestId("showcase-save-btn")).toBeVisible();
  await page.getByTestId("showcase-save-btn").tap();
  await expect(page.getByTestId("photoshoot-look")).toBeVisible();
  await expect(page.getByRole("link", { name: "GO BACK" })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-landscape.png`, scale: "css" });
  expect(errors).toEqual([]);
  expect(consoleErrors).toEqual([]);
  expect(failedRequests).toEqual([]);
  expect(badResponses).toEqual([]);
});
