import { expect, test } from "@playwright/test";

test("touch outfit selection, full character and photoshoot on a phone", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/play");
  await page.getByTestId("garment-top-modal-grommet").tap();
  await page.getByTestId("mobile-category-bottoms").tap();
  await page.getByTestId("garment-bottom-sculpted-jeans").tap();
  await page.getByTestId("mobile-category-shoes").tap();
  await page.getByTestId("garment-shoes-mary-janes").tap();
  const stage = page.getByTestId("studio-stage");
  await expect(stage).toHaveAttribute("data-layer-count", "3");
  await stage.locator("img").evaluateAll((images) => Promise.all(images.map((image) => (image as HTMLImageElement).decode())));
  const box = (await stage.boundingBox())!;
  expect(box.height / box.width).toBeCloseTo(1.5, 1);
  expect(box.y).toBeGreaterThanOrEqual(0);
  expect(box.y + box.height).toBeLessThan((await page.getByRole("button", { name: "SHOW YOUR LOOK" }).boundingBox())!.y);
  await expect(page.getByTestId("foreground-arms")).toHaveCSS("z-index", "38");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-play.png`, scale: "css" });
  await page.getByRole("button", { name: "SHOW YOUR LOOK" }).tap();
  await expect(page).toHaveURL(/\/photoshoot/);
  await expect(page.getByTestId("photoshoot-look")).toBeVisible();
  const actor = (await page.getByTestId("photoshoot-look").boundingBox())!;
  const frame = (await page.getByTestId("photoshoot-frame").boundingBox())!;
  expect(actor.height).toBeGreaterThan(180);
  expect(actor.y).toBeGreaterThanOrEqual(frame.y);
  expect(actor.y + actor.height).toBeLessThanOrEqual(frame.y + frame.height + 1);
  expect(actor.height / actor.width).toBeCloseTo(1.5, 1);
  await page.getByRole("link", { name: "GO BACK" }).scrollIntoViewIfNeeded();
  await expect(page.getByRole("button", { name: "SAVE", exact: true })).toBeInViewport();
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-photoshoot.png`, fullPage: true, scale: "css" });
  await page.getByRole("link", { name: "GO BACK" }).tap();
  await expect(page.locator('[data-garment="bottom-sculpted-jeans"]')).toBeVisible();
  await page.setViewportSize({ width: 844, height: 390 });
  await expect(stage).toBeInViewport();
  await expect(page.getByRole("button", { name: "SHOW YOUR LOOK" })).toBeInViewport();
  await page.getByRole("button", { name: "SHOW YOUR LOOK" }).tap();
  await expect(page.getByTestId("photoshoot-look")).toBeVisible();
  await expect(page.getByRole("link", { name: "GO BACK" })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/mobile/${testInfo.project.name}-landscape.png`, scale: "css" });
  expect(errors).toEqual([]);
});
