export const STAGE = Object.freeze({ width: 1024, height: 1536 });
const outputRoot = process.env.STUDIO_OUTPUT_ROOT || "public/game/studio";

export const PATHS = Object.freeze({
  model: "assets/studio/source/model-master-straight-nude.png",
  sourceWorn: "assets/studio/source/worn",
  runtimeLayers: `${outputRoot}/layers`,
  previews: `${outputRoot}/previews`,
  qa: "artifacts/studio-qa/assets",
  validationReport: "artifacts/studio-qa/pipeline-validation.json",
});

export const INTERACTIONS = Object.freeze({
  tallBootId: "shoes-brown-boots",
  tallBootClipRatio: 0.648,
  longBottomIds: ["bottom-blue-jeans"],
});

export const QUALITY_LIMITS = Object.freeze({
  minimumVisiblePixels: 1_500,
  minimumPreviewDimension: 40,
  previewOccupancyMin: 0.5,
  previewOccupancyMax: 0.94,
  expectedCategories: { tops: 6, bottoms: 6, shoes: 2 },
});

export const CONFIGS = Object.freeze({
  "top-white-basic": {
    category: "tops",
    name: "Áo hai dây trắng basic",
    minY: 230,
    maxY: 660,
    minX: 350,
    maxX: 670,
    threshold: 25,
    previewPalette: "lightNeutral",
  },
  "top-black-tee": {
    category: "tops",
    name: "Áo thun đen",
    minY: 205,
    neckMinY: 235,
    neckX: { min: 450, max: 574 },
    maxY: 675,
    minX: 300,
    maxX: 720,
    threshold: 25,
    previewPalette: "darkNeutral",
  },
  "top-white-lace": {
    category: "tops",
    name: "Áo trắng dài tay viền ren",
    minY: 180,
    neckMinY: 270,
    neckX: { min: 440, max: 584 },
    maxY: 815,
    waistMaxY: 700,
    waistX: { min: 400, max: 624 },
    minX: 280,
    maxX: 740,
    threshold: 22,
    previewPalette: "lightNeutral",
  },
  "top-gray-v": {
    category: "tops",
    name: "Áo len xám cổ V",
    minY: 200,
    neckMinY: 250,
    neckX: { min: 440, max: 584 },
    maxY: 755,
    minX: 280,
    maxX: 740,
    threshold: 25,
    previewPalette: "neutral",
  },
  "top-ivory-pointelle": {
    category: "tops",
    name: "Áo dệt kim kem",
    minY: 230,
    maxY: 628,
    minX: 350,
    maxX: 670,
    threshold: 22,
    previewPalette: "ivory",
    decolletage: { minX: 440, maxX: 584, minY: 350, maxY: 425 },
  },
  "top-red-offshoulder": {
    category: "tops",
    name: "Áo đỏ trễ vai tay loe",
    minY: 275,
    maxY: 865,
    waistMaxY: 636,
    waistX: { min: 390, max: 634 },
    filterSkinAtWaist: true,
    minX: 270,
    maxX: 750,
    threshold: 25,
    previewPalette: "red",
  },
  "bottom-blue-jeans": {
    category: "bottoms",
    name: "Quần jeans xanh",
    minY: 560,
    maxY: 1370,
    minX: 320,
    maxX: 700,
    threshold: 25,
    filterBodyArtifacts: true,
    keepLargestComponent: true,
  },
  "bottom-white-shorts": {
    category: "bottoms",
    name: "Quần short trắng",
    minY: 565,
    maxY: 870,
    minX: 330,
    maxX: 690,
    threshold: 22,
    filterBodyArtifacts: true,
    keepLargestComponent: true,
  },
  "bottom-black-mini": {
    category: "bottoms",
    name: "Váy ngắn đen",
    minY: 560,
    maxY: 880,
    minX: 330,
    maxX: 690,
    threshold: 25,
    filterBodyArtifacts: true,
    keepLargestComponent: true,
  },
  "bottom-navy-dots": {
    trimLightExterior: true,
    preserveContinuousFabric: true,
    fillBetweenEdges: true,
    category: "bottoms",
    name: "Váy navy chấm bi",
    minY: 550,
    maxY: 1220,
    minX: 280,
    maxX: 740,
    threshold: 25,
    filterBodyArtifacts: true,
    keepLargestComponent: true,
  },
  "bottom-white-pleats": {
    preserveContinuousFabric: true,
    onlyNeutral: true,
    category: "bottoms",
    name: "Váy xếp ly trắng viền ren",
    minY: 560,
    maxY: 880,
    minX: 300,
    maxX: 720,
    threshold: 10,
    filterSkin: true,
    keepLargestComponent: true,
    fillBetweenEdges: true,
  },
  "bottom-gray-maxi": {
    trimLightExterior: true,
    preserveContinuousFabric: true,
    fillBetweenEdges: true,
    category: "bottoms",
    name: "Váy dài xếp ly xám",
    minY: 555,
    maxY: 1330,
    minX: 280,
    maxX: 740,
    threshold: 25,
    filterBodyArtifacts: true,
    keepLargestComponent: true,
  },
  "shoes-mary-janes": {
    previewPalette: "darkNeutral",
    category: "shoes",
    name: "Giày Mary Jane đen",
    minY: 1340,
    maxY: 1515,
    minX: 370,
    maxX: 650,
    threshold: 25,
  },
  "shoes-brown-boots": {
    category: "shoes",
    name: "Boots nâu cao cổ",
    minY: 975,
    maxY: 1525,
    minX: 300,
    maxX: 720,
    threshold: 14,
    onlyDark: true,
  },
});
